# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 280a053c1aedf1b1feb3cafcfa04562eec5ea9d991387bd7679f04fbced35b6cb08689cf2e5382fc6a01420967bafa4157d55562cb98e78bf20e614a2e01e473

test:
  secret_key_base: e6200b4acbf39443f40bc05aae06799ca850a25806f00a21dfb7a6e2de95fa38247dd6c1f135a2af42eea2cb7d5d408258699f98f03bfd38e74e72c40c0b26e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
